<a href="https://colab.research.google.com/github/rajlaxmi-21/Pytorch/blob/main/Pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

###Why tensors?
-> optimized for automatic differentiation

-> can run on GPUS/hardware accelerators

###What does it store?
->inputs, outputs

->model parameters

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

##TENSORS FROM NUMPY ARRAY

In [4]:
np_arr = np.array(data)

In [5]:
x_np = torch.from_numpy(np_arr)

#TENSORS FROM ANOTHER TENSOR

In [6]:
x_ones = torch.ones_like(x_data)
print(x_ones)

#overrides dtype of x_data
x_rand = torch.rand_like(x_data, dtype = torch.float32)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1518, 0.3667],
        [0.8554, 0.0317]])


In [12]:
shape = (3,2)

rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [13]:
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.7541, 0.2907],
        [0.6191, 0.3188],
        [0.2876, 0.9939]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


##ATTRIBUTES OF A TENSOR

In [15]:
print("Shape: ", rand_tensor.shape)
print("Datatype: ", rand_tensor.dtype)
print("Device tensor is stored on: ", rand_tensor.device)

Shape:  torch.Size([3, 2])
Datatype:  torch.float32
Device tensor is stored on:  cpu


##OPERATIONS ON TENSORS

In [16]:
tensor = torch.ones(4,4)

In [18]:
print(f"First row: {tensor[0,:]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[:,-1]}")

tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


# Joining tensors

-> torch.cat

-> torch.stack

In [21]:
t1 = torch.cat([tensor, tensor], dim=0)
t1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Arithmetic operations

MATRIX MUL

In [24]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

print(y1)
print(y2)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


ELEMENT WISE MUL

In [29]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)
print(z1)
print(z2)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


TENSOR 1X1 DIM -> SCALAR



In [30]:
agg = tensor.sum()

In [31]:
type(agg)

torch.Tensor

In [32]:
agg_item = agg.item()

In [33]:
print(agg_item, type(agg_item))

12.0 <class 'float'>


IN-PLACE OPERATIONS -> _

In [35]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]]) 

tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


## BRIDGE WITH NUMPY ARRAYS

TENSOR TO NUMPY ARRAY

In [36]:
t = torch.ones(5)
print(t)

n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [37]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


NUMPY ARRAY TO TENSOR

In [38]:
n = np.ones(5)
t = torch.from_numpy(n)

In [39]:
np.add(n, 1, out=n)
print(n)
print(t)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
