<a href="https://colab.research.google.com/github/rajlaxmi-21/Pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
torch.cuda.is_available() # returns if gpu is present

True

# CREATING TENSORS

In [ ]:
#using empty
a= torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(1,4)

tensor([[0., 0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.4413, 0.2144, 0.0647],
        [0.2586, 0.4474, 0.7432]])

In [ ]:
#using seed
torch.manual_seed(1)
torch.randn(2,3)

tensor([[ 0.6614,  0.2669,  0.0617],
        [ 0.6213, -0.4519, -0.1661]])

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

# TENSOR SHAPES

In [ ]:
x= torch.tensor([[[1,2,3,4],[4,2,1,2]],[[1,2,3,3],[1,3,1,3]]])

In [ ]:
x.shape

torch.Size([2, 2, 4])

In [ ]:
 torch.empty_like(x)

tensor([[[138423038736176, 138422745505008, 138423041203760, 138422745533568],
         [138427613197104,             129, 138427620682976, 138427620682976]],

        [[138422745533680,       193871472, 138422745505808,         9899040],
         [138422745533872, 138427601394096, 138427601389808,        10793584]]])

In [ ]:
torch.zeros_like(x)

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[[0.6826, 0.3051, 0.4635, 0.4550],
         [0.5725, 0.4980, 0.9371, 0.6556]],

        [[0.3138, 0.1980, 0.4162, 0.2843],
         [0.3398, 0.5239, 0.7981, 0.7718]]])

## TENSOR DATA TYPES

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([[1.0,2.0],[3.0,4.0]], dtype=torch.int32)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [ ]:
torch.tensor([[1,2]],dtype=torch.float64)

tensor([[1., 2.]], dtype=torch.float64)

In [ ]:
x.to(torch.float32)

tensor([[[1., 2., 3., 4.],
         [4., 2., 1., 2.]],

        [[1., 2., 3., 3.],
         [1., 3., 1., 3.]]])

# MATHEMATICAL OPS

In [ ]:
x = torch.tensor([[1,2],[5,6]])

In [ ]:
# addition
x+2
#sub
x-2
#mult
x*2
#div
x/2
#intdiv
x//2
#mod
x%2
#power
x**2

tensor([[ 1,  4],
        [25, 36]])